name: 'Pr Checks'
description: 'Return if all checks are successful'
author: 'peterjgrainger'
inputs:
  approvalsRequired:
    required: true
    description: 'number of reviews required'
  pr:
    required: false
    description: run this check against a single PR
runs:
  using: 'node16'
  main: 'dist/index.js'
